# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15efef49b63b7a95ecb2295298a7cda5868b104dbe3c2e7dbe7a25e1a99f65b1531e046838ba0e1db1a572e8c3d63b99f50666969b0f6118ed2a9e40c2cd3006

test:
  secret_key_base: 6453d94b19609afeb4e00b33cc504417c123ae186ed43e1d58dd88e80baad58373170769f748773df567e940316c27dfe43df3b8b8b039ac6e69646c92cb95d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
